doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 120
autodetect: true
requirements:
  - coverage
  - coveralls
  - docopt
  - h5py
  - lxml
  - numpy
  - PyQt
  - pyRestTable
  - requests
ignore-paths:
  - _installer.py
  - docs
  - install_NXDL_file_sets.py
  - punx/_version.py
  - punx/cache
  - punx/data
  - punx/ignore_now
  - versioneer.py
ignore-patterns:
  - (^|/)docs(/|$)
  - ^example/doc_.*\.py$
python-targets:
  - 3
pylint:
  disable:
    - arguments-differ
    - cyclic-import
    - protected-access
    - unused-argument
