name: punx

channels:
  - defaults
  - conda-forge

dependencies:
  - coverage
  - pytest

  - pip:
    # as seen: https://github.com/bleachbit/bleachbit/commit/c66b604b2702e51b215a9e768c93b099d1331fc4
    - coveralls
    - pyyaml
