name: Publish Sphinx Docs to GitHub Pages

on:
  # Build the docs on pushes to main branch, PRs to main branch, and new tags.
  # Publish only on demand.
  push:
    branches:
      - main
    tags:
      - '*'  # all tags
  pull_request:
    branches:
      - main
  workflow_dispatch:   # allow manual triggering
    inputs:
      deploy:
        description: 'Deploy documentation'
        type: boolean
        required: true
        default: false

jobs:

  pages:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy Information
      if: ${{ github.event.inputs.deploy }}
      run: |
        echo "The docs will be published from this workflow run."

    - name: Make Temporary Directory for Sphinx content
      run: |
        echo "SRC_DIR=$(pwd)" >> ${GITHUB_ENV}
        echo "TMP_DIR=$(mktemp -d)" >> ${GITHUB_ENV}
        # next step also creates _version.py file
        echo "VERSION=$(./setup.py --version)" >> ${GITHUB_ENV}

    - name: Build and Commit
      uses: sphinx-notes/pages@v3
      with:
        # path to conf.py directory
        documentation_path: ./docs/source
        requirements_path: ./docs/requirements.txt
        publish: false

    - name: Publish (push gh-pages branch) only on demand
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event.inputs.deploy }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.TMP_DIR }}
        force_orphan: true
