name: Unit Tests

on: [push, pull_request]

jobs:
  build-linux:
    name: CI py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: anaconda-test-env-py-${{ matrix.python-version }}

    - name: Initial diagnostics
      shell: bash -l {0}
      run: |
        micromamba env list
        micromamba info
        micromamba list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Install Python package & test requirements
      shell: bash -l {0}
      run: |
        micromamba install "coverage<=5.0a5" coveralls pytest

    # - name: Install YAML packages
    #   shell: bash -l {0}
    #   run: |
    #     micromamba install pyyaml ruamel_yaml yaml -c conda-forge

    - name: Diagnostic
      shell: bash -l {0}
      run: |
        micromamba list

    - name: Run tests with pytest & coverage
      shell: bash -l {0}
      run: |
        coverage run --concurrency=thread --parallel-mode -m pytest -vvv .
        coverage combine

    - name: Coverage Report
      shell: bash -l {0}
      run: |
        coverage report

    - name: Upload to coveralls
      shell: bash -l {0}
      # https://github.com/TheKevJames/coveralls-python
      run: |
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
